services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mpd_app_local
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - mpd_network

  db_local:
    image: postgis/postgis:17-3.5
    container_name: mpd_db_local
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres:/var/lib/postgresql
    networks:
      - mpd_network

  redis:
    image: redis:8
    container_name: mpd_redis_local
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - mpd_network

networks:
  mpd_network:
    driver: bridge

volumes:
  pgdata:
  redisdata: